FROM ubuntu:20.04

MAINTAINER vetalsmith
 
# Apache ENVs
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_PID_FILE /var/run/apache2/apache2.pid
ENV APACHE_SERVER_NAME localhost

ARG DEBIAN_FRONTEND="noninteractive"
ARG DEBCONF_NOWARNINGS="yes"
ARG DEBCONF_TERSE="yes"
ARG APT="apt-get -qq -y"
ARG LANG="C.UTF-8"

#INSTALL

RUN apt-get update
RUN apt-get install -y apache2 php curl
RUN echo "<?php phpinfo(); ?>" | tee /var/www/html/index.php

RUN a2enmod ssl
RUN a2ensite default-ssl
RUN service apache2 reload

# Expose HTTP
EXPOSE 80

# Launch Apache
CMD ["apachectl", "-D",  "FOREGROUND"]
